---
# auditd config tasks

- name: Install requirements
  ansible.builtin.package:
    name: bash
    state: present

- name: Install audit
  ansible.builtin.package:
    name: "{{ auditd_packages }}"
    state: present

- name: Configure auditd
  ansible.builtin.template:
    src: "{{ auditd_config_file }}.j2"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify: [ Restart auditd ]

- name: Create rules.d directory
  ansible.builtin.file:
    path: "{{ auditd_config_directory }}/{{ auditd_custom_rules_directory }}"
    state: directory
    mode: "0750"

- name: Place custom rules
  ansible.builtin.copy:
    src: rules/
    dest: "{{ auditd_config_directory }}/{{ auditd_custom_rules_directory }}"
    mode: "0664"
  notify: [ Run augenrules ]

- name: Start and enable auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: started
    enabled: yes

- name: Create reports directory
  ansible.builtin.file:
    path: "{{ auditd_report_directory }}"
    state: directory
    mode: "0750"
  tags: [ config ]
