---
# tasks file for lynis-role

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags: [ config ]

- name: Import scan tasks
  ansible.builtin.import_tasks: scan.yml
  tags: [ lynis_scan ]

- name: Import report tasks
  ansible.builtin.import_tasks: report.yml
  tags: [ lynis_report ]
